replicaCount: 2

image:
  repository: ""  
  tag: "latest"    
  pullPolicy: IfNotPresent

namespace: dev

serviceAccount:
  name: auth-service-sa

configMap:
  name: auth-service-config

secrets:
  mongodb:
    name: mongodb-secret
    key: connection-string
  jwt:
    name: auth-service-secret
    key: jwt-secret
